### ISSUE TITLE
Not authorized to perform: acm:ListCertificates

### ISSUE THREAD

**Issue by whiskeysierra** [zalando-incubator/stups2go#37]
I saw the following error today:

> An error occurred (AccessDeniedException) when calling the ListCertificates operation: User: arn:aws:sts::666730286221:assumed-role/go-agent-b25g07dc250agent-GoAgentRole-TIGRX76HRE0U/i-0fae3fd94a5929cf5 is not authorized to perform: acm:ListCertificates

I worked around it by adding `acm:*` to the list of allowed actions in the IAM policy. If this is really needed we should probably add it to the senza file.

I'm actually not sure what changed as to why we need this now and not earlier. My assumption is that has to do with the recent Senza update.

**Comment by hjacobs** [comment]
@whiskeysierra we now use ACM certs by default. So yes, we need to allow "acm:List*".

**Comment by whiskeysierra** [comment]
Would `acm:*` be unsafe?

**Comment by hjacobs** [comment]
@whiskeysierra not necesarily, but we only need "acm:List*", so I would not grant more.
